name: Python Package Publish

on:
  push:
    branches:
      - main  # Trigger the workflow when pushing to the main branch

jobs:
  build:
    runs-on: ubuntu-latest  # Use the latest Ubuntu runner

    steps:
    - name: Checkout code
      uses: actions/checkout@v2  # Checkout the repository's code

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: "3.8"  # Use Python version 3.8 (or your version)

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install setuptools wheel twine  # Install necessary tools for packaging and uploading

    - name: Build package
      run: |
        python setup.py sdist bdist_wheel  # Build the source distribution and wheel file

    - name: Upload package to PyPI
      env:
        TWINE_USERNAME: ${{ secrets.PYPI_USERNAME }}  # PyPI username stored in GitHub secrets
        TWINE_PASSWORD: ${{ secrets.PYPI_PASSWORD }}  # PyPI password stored in GitHub secrets
      run: |
        twine upload dist/*  # Upload the package to PyPI
